### ISSUE TITLE
Bug: infinite loop in case of incorrect input

### ISSUE THREAD

**Issue by LostInKadath** [ivanhi0/Calc_Test_C-#3]
Steps:
1. Launch app;
2. When choosing mode, print some non-numeric chars -- for example, letters, like `abc`; then press _Enter_;
3. When getting error, press _Enter_ as any key.

Expected:
App returns to choose mode screen.

In fact:
App gets stuck in an infinite loop.

**Comment by ivanhi0** [comment]
Fixed, Thank you
